name = "blogiec"
compatibility_date = "2025-07-08"

[site]
bucket = "./build"

[build]
command = "npm run build"

[pages]
build_output_dir = "./build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
